# Generated by Django 4.2.4 on 2023-09-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalbilling',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='parkingbilling',
            name='elapsed_time',
        ),
    ]
