# Generated by Django 4.2.2 on 2023-08-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_alter_parkinglot_description_alter_parkinglot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Billing',
            },
        ),
        migrations.AlterModelTable(
            name='parkinglot',
            table='ParkingLot',
        ),
        migrations.AlterModelTable(
            name='parkingslot',
            table='ParkingSlot',
        ),
    ]
