# Generated by Django 4.2.2 on 2023-08-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0006_billing_alter_parkinglot_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.parkingslot')),
            ],
            options={
                'db_table': 'ParkingBilling',
            },
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
