# Generated by Django 4.2.2 on 2023-08-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0008_alter_parkingslot_slot_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingbilling',
            old_name='car_number',
            new_name='vehicle_number',
        ),
    ]
