# Generated by Django 4.2.2 on 2023-08-25 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0009_rename_car_number_parkingbilling_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingbilling',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
