# Generated by Django 4.2.2 on 2023-08-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0010_parkingbilling_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingbilling',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parkingbilling',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
