# Generated by Django 4.2.2 on 2023-08-27 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0014_alter_parkingbilling_parking_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parking_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_app.parkingslot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Final Billing',
            },
        ),
    ]
