# Generated by Django 4.2.2 on 2023-08-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0015_finalbilling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Enter name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
            ],
            options={
                'db_table': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Subscriber Email')),
            ],
            options={
                'db_table': 'Subscriber',
            },
        ),
    ]
