# Generated by Django 4.2.4 on 2023-08-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0016_contactus_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='parking_type',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], default=1, max_length=20, verbose_name='Parking Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking_slot_type',
            field=models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Four Wheeler', 'Four Wheeler'), ('Heavy Vechiles', 'Heavy Vechiles')], default=1, max_length=30, verbose_name='Parking Slot Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingbilling',
            name='total_cost',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
       
    ]
