# Generated by Django 4.2.4 on 2023-08-31 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0018_parkingrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbilling',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='finalbilling',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='parkingbilling',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='parkingbilling',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
