# Generated by Django 4.2.4 on 2023-08-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0019_alter_finalbilling_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalbilling',
            name='elapsed_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
