# Generated by Django 4.2.4 on 2023-08-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0020_finalbilling_elapsed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingbilling',
            name='elapsed_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
